ENV['AWS_ACCESS_KEY_ID'] = 'AKIAIQDMPQ6RQZQ2HLHA'
ENV['AWS_SECRET_ACCESS_KEY'] = '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'

# ENV['EMAIL_USERNAME'] = 'answerawesome@gmail.com'
# ENV['EMAIL_PASSWORD'] = 'Sup3r$ecret$$'
